### ISSUE TITLE
Permission denied Issue

### ISSUE THREAD

**Issue by rubab-azim** [Manty-K/Rapid-Note#1]
Creation failed, path = '/storage/emulated/0/Rapid Note' (OS Error: Permission denied, errno = 13).
"android.permission.MANAGE_EXTERNAL_STORAGE"  this permission is also required for some devices beacuse my device os version is 12 and i was having this exception.

**Comment by oyerottiii** [comment]
Still it shows a error namely, errno 13

**Comment by oyerottiii** [comment]
any update on this?

**Comment by Manty-K** [comment]
Try adding the following code in **AndroidManifest.xml**:
```
<application 
      android:requestLegacyExternalStorage="true"
```
